Proposition encodage lettre 203 205
axellelecroq/apollinaire-project pull request #44
Opened 2021-02-14 12:55 UTC by leaprs

Bonjour à tous, 

Je vous soumets pour validation ma proposition d'encodage de la lettre du folio 203 qui contient un écriture verticale (https://gallica.bnf.fr/ark:/12148/btv1b525088021/f203.item.r=Apollinaire%20manuscrits).

Pour l'encoder, j'ai choisi un élément ```<space>``` qui a l'exclusivité de l'attribut ``` @dim ``` permettant l'indication d'une valeur verticale (https://www.tei-c.org/release/doc/tei-p5-doc/fr/html/ref-space.html). J'ai été contraint de placer cet élément avant ``` <closer> ``` car on ne peut mettre de balise ``` <p> ``` à la suite d'un ``` <closer> ```.

Si cela vous convient, je peux merger cette branche dans ma branche de travail pour les lettres.

P.S.: j'ai mis en reviewers les personnes du groupe dossier de presse mais tout le monde est bien sûr libre de donner son avis.

2021-02-14 13:25 UTC, axellelecroq commented
Je trouve cette proposition très bien. Je vais d'ailleurs l'ajouter pour le folio 178 que l'on avait encodé ensemble lors du prototype et pour laquelle nous n'avions pas indiqué que c'était écrit verticalement.

2021-02-16 14:22 UTC, D0riane commented
Bonjour, 
Après avoir lu les tei guidelines, je me trompe peut être mais j'ai l'impression que `<space>` est à utiliser pour un espace vide. Ici, ça voudrait dire un espace vide vertical sur la gauche, ce qui ne correspond pas tout à fait à la situation.. Serait il pas mieux d'utiliser un `<p>` une valeur "vertical" sur un attribut `@rend` ?

2021-02-16 14:41 UTC, leaprs commented
@D0riane merci pour ta réponse, effectivement il y a une certaine ambiguïté car à la fois, c'est indiqué que l'élément ``` <space> ``` est utilisé pour signifier "un espace significatif dans le texte édité" mais d'un autre côté, dans les exemples, ce n'est pas très clair.
Ta proposition me convient également : je propose que si quelqu'un est d'accord, qu'il rajoute un pouce sur cette dernière.

2021-02-16 14:43 UTC, HugoSchtr requested changes
Je suis la proposition de @D0riane, un ```<p>``` solo semble mieux adapté. Pour ```@rend```, je proposerais la valeur "landscape" ou "paysage." J'ai peur qu'on comprenne avec "vertical" que ce soit écrit comme ça :
H
E
L
L
O
(après c'est une distinction pointilleuse, "vertical" me convient sinon)

Je pense que la contrainte du ```<closer>``` dont tu parles @leaprs est pratique, on comprend comme ça que cette phrase fait quand même partie de la lettre, malgré son emplacement.

2021-02-16 14:47 UTC, axellelecroq commented
Je suis d'accord avec les propositions de @D0riane et de @HugoSchtr !
Ainsi, si je comprends bien, l'exemple deviendrait : 
```
<p><!--  encodage lettre --></p>
<p rend="align(left) format(landscape)">Comme je me souviens du Festin d'Esope !</p>
<closer><!-- encodage closer --></closer>
```

2021-02-16 14:52 UTC, HugoSchtr commented
@axellelecroq 
<p><!--  encodage lettre --></p>
<p rend="lavaleurquondecidera">Comme je me souviens du Festin d'Esope !</p>
<closer><!-- encodage closer --></closer>
Plutôt comme ça ! ```@format``` ne peut pas être mis sur un ```<p>``` (https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-p.html)

2021-02-16 14:59 UTC, axellelecroq commented
Dans ma proposition, il s'agit d'une valeur au sein de l'attribut `@rend` et non de l'attribut `@format` en lui-même, il me semble que ça fonctionne non ?

2021-02-16 15:10 UTC, HugoSchtr commented
Oups autant pour moi je ne le savais pas. Ta proposition me convient dans ce cas. :)

2021-02-16 19:48 UTC, leaprs commented
Merci à tous, j'ai modifié mon document suivant le modèle décrit par @axellelecroq ! Quelqu'un peut merger la branche si tout est ok :)

2021-02-17 08:52 UTC, D0riane approved these changes

2021-02-17 08:56 UTC, HugoSchtr approved these changes
C'est parfait ! Merci !

2021-02-17 09:15 UTC, merged