Encodages des articles folios 154-164 et 200, 201, 202 et 206.
axellelecroq/apollinaire-project pull request #64
Opened 2021-02-21 18:47 UTC by HugoSchtr

Bonsoir ! 

Voici ma part d'encodages pour les articles du dossier de presse. J'attends vos retours pour modifier toute erreur ou coquille. :)

2021-02-21 19:22 UTC, axellelecroq requested changes
J'ai ajouté quelques commentaires directement dans ton encodage :)

2021-02-21 19:22 UTC, axellelecroq commented on dossierdepresse/encodage_articles/articles_group.xml
> +                  <p>Uebertragen von <persName ref="#max_cahén_fritz">Fritz Max Cahén</persName></p>
Fritz Max est son prénom et Cahen son nom.
Son `xml:id` devrait donc être `cahen_fritz_max`

2021-02-21 19:22 UTC, axellelecroq commented on dossierdepresse/encodage_articles/articles_group.xml
> +                     Paris, Mercure de France.</head>
Mercure de France à indexer ?

2021-02-21 19:22 UTC, axellelecroq commented on dossierdepresse/encodage_articles/articles_group.xml
> +                        <metamark function="header" rend="align(center) caps">A <persName
peut-être rajouter `case` dans l'attribut `@rend` ?
Cela donnerait : 
`<metamark function="header" rend="align(center) case(caps)">

2021-02-21 19:22 UTC, axellelecroq commented on dossierdepresse/encodage_articles/articles_group.xml
> +                        target="#l_Ermite" rend="italic">l’Ermite</ref> : <quote rend="italic">
Nous avions décidé (issue #47) de ne pas utiliser les majuscules dans les `xml:id`. Concernant la normalisation des `xml:id`, il y a un fichier qui les rassemble toutes [sur le github](https://github.com/axellelecroq/apollinaire-project/blob/main/documentation/regles_nommage.md).

2021-02-21 19:22 UTC, axellelecroq commented on dossierdepresse/encodage_articles/articles_group.xml
> +                           />(tournaient:dans l'interligne, pour terminer le vers malgré le manque
commentaire de transcription à supprimer de l'encodage.

2021-02-21 19:22 UTC, axellelecroq commented on dossierdepresse/encodage_articles/articles_group.xml
> +                  <p><ref>Jack Mercereau</ref></p>
`xml:id` manquante

2021-02-21 19:22 UTC, axellelecroq commented on dossierdepresse/encodage_articles/articles_group.xml
> +                     le petit restaurant du <placeName ref="#boulevard_saint_germain">bou- <lb
Je ne sais plus ce qu'on s'était dit lors du visio mais il me semblait que pour les adresses précises/noms de rues, on avait, me semble- t-il, d'indexer seulement les villes. 
Ainsi les noms des rues seraient indexées sous le nom de la ville dans laquelle elle se trouve, ici serait donc Paris.
Néamoins, aucune décision n'avait été prise, sauf erreur de ma part, et je pense que c'est un sujet qui mériterait discussion.

2021-02-22 11:05 UTC, D0riane reviewed
Bonjour ! 
Ton encodage est très bien, mes corrections sont assez minimes. Elles portent surtout sur des `<lb break="no"/>` oubliés et les références aux poèmes de Alcools !
Je n'ai pas répété les commentaires d' @axellelecroq mais je suis d'accord avec elle, notamment sur la question de l'indexation des lieux au niveau des villes.

2021-02-22 12:12 UTC, HugoSchtr commented on dossierdepresse/encodage_articles/articles_group.xml
> +                           Apollinaire</emph></persName>, <ref target="#alcools">Alcools</ref>.
Oui effectivement, j'ai décidé de ne pas tenir à jour le fichier group et de m'en tenir uniquement pour le moment aux encodages individuels. Group sera mis à jour à partir des encodages individuels une fois le merge de la PR :)
Dans les encodages individuels, Alcools n'est pas indexé.

2021-02-22 12:13 UTC, HugoSchtr commented on dossierdepresse/encodage_articles/articles_group.xml
> +                  <p>Uebertragen von <persName ref="#max_cahén_fritz">Fritz Max Cahén</persName></p>
Modification faite !

2021-02-22 12:14 UTC, HugoSchtr commented on dossierdepresse/encodage_articles/articles_group.xml
> +                     Paris, Mercure de France.</head>
Modification faite !

2021-02-22 12:16 UTC, HugoSchtr commented on dossierdepresse/encodage_articles/articles_group.xml
> +                        <metamark function="header" rend="align(center) caps">A <persName
case à la place de caps ?

2021-02-22 12:17 UTC, HugoSchtr commented on dossierdepresse/encodage_articles/articles_group.xml
> +                        target="#l_Ermite" rend="italic">l’Ermite</ref> : <quote rend="italic">
Erreur de ma part, c'est modifié !

2021-02-22 12:18 UTC, HugoSchtr commented on dossierdepresse/encodage_articles/articles_group.xml
> +                           />(tournaient:dans l'interligne, pour terminer le vers malgré le manque
C'est modifié !

2021-02-22 12:19 UTC, HugoSchtr commented on dossierdepresse/encodage_articles/articles_group.xml
> +                  <p><ref>Jack Mercereau</ref></p>
Modification faite !

2021-02-22 12:20 UTC, HugoSchtr commented on dossierdepresse/encodage_articles/articles_group.xml
> +                     le petit restaurant du <placeName ref="#boulevard_saint_germain">bou- <lb
Oui effectivement, je simplifie les placeName du coup.

2021-02-22 12:24 UTC, HugoSchtr commented on dossierdepresse/encodage_articles/200_article.xml
> +               se disputent la con— <lb/>quête de la postérité. Toutes deux ont <lb/>leur vérité et
Modification faite !

2021-02-22 12:25 UTC, HugoSchtr commented on dossierdepresse/encodage_articles/200_article.xml
> +               effort symboliste qui aux envi— <lb break="np"/>rons de 1880 a opposé l‘idéalisme à
Modification faite !

2021-02-22 12:25 UTC, HugoSchtr commented on dossierdepresse/encodage_articles/200_article.xml
> +               <lb/>œuvres qui ont leur beauté et retien— <lb/>nent l‘attention. Leur différence est
Modification faite !

2021-02-22 12:26 UTC, HugoSchtr commented on dossierdepresse/encodage_articles/200_article.xml
> +               <lb/>moins dans la façon dont elles s‘effor— <lb/>cent d‘échapper aux influences
Modification faite !

2021-02-22 12:26 UTC, HugoSchtr commented on dossierdepresse/encodage_articles/200_article.xml
> +               plus délicieuse expression <lb/>poétique de la première jeunesse, de cel— <lb/>le qui
Modification faite !

2021-02-22 12:26 UTC, HugoSchtr commented on dossierdepresse/encodage_articles/200_article.xml
> +               l‘autre jeunes— <lb/>se, moins sentimentale, oppose la sienne <lb/>et l‘œuvre
Modification faite !

2021-02-22 12:27 UTC, HugoSchtr commented on dossierdepresse/encodage_articles/200_article.xml
> +                  <lb/>linaire</persName> publie aux éditions du Mercure <lb/>de France a le mérite
Modification faite !

2021-02-22 12:27 UTC, HugoSchtr commented on dossierdepresse/encodage_articles/200_article.xml
> +               réuni les éléments indica— <lb/>tifs d‘une poésie hardie, purement in—
Modification faite !

2021-02-22 12:28 UTC, HugoSchtr commented on dossierdepresse/encodage_articles/200_article.xml
> +               <lb/>tellectuelle, où les souvenirs personnels <lb/>ne communiquent au cœur qu‘une
Modification faite !

2021-02-22 12:28 UTC, HugoSchtr commented on dossierdepresse/encodage_articles/200_article.xml
> +               <lb/>En vérité ce livre est un des plus cu— <lb/>rieux qui aient paru au cours de ces
modification faite !

2021-02-22 12:29 UTC, HugoSchtr commented on dossierdepresse/encodage_articles/200_article.xml
> +               d‘idées généra— <lb/>les dont, pour le moins qu‘on puisse di— <lb break="no"/>re,
modification faite !

2021-02-22 12:29 UTC, HugoSchtr commented on dossierdepresse/encodage_articles/200_article.xml
> +               <lb/>constituent sa vie : <lb/>et quel symbolisme plus inquiet que ce— <lb/>lui que
modification faite !

2021-02-22 12:32 UTC, HugoSchtr commented on dossierdepresse/encodage_articles/200_article.xml
> +                  rend="small italic">
Merci ! Modification faite

2021-02-22 12:33 UTC, HugoSchtr commented on dossierdepresse/encodage_articles/202_article.xml
> +               saurez que <lb/>s‘il confesse : <quote>
Merci ! Modification faite

2021-02-22 12:35 UTC, HugoSchtr commented on dossierdepresse/encodage_articles/202_article.xml
> +               vers la danse de <lb/>Salomé : <quote>« Prends, dit—elle au fou du roi, <lb/>« Prends
Merci ! Modification faite

2021-02-22 12:36 UTC, HugoSchtr commented on dossierdepresse/encodage_articles/202_article.xml
> +                  <l>Dans la cour je pleure à Paris</l>
Merci ! Modification faite

2021-02-22 12:40 UTC, HugoSchtr commented on dossierdepresse/encodage_articles/202_article.xml
> +                  <quote rend="align(center)">
Merci ! Modification faite

2021-02-22 12:41 UTC, HugoSchtr commented on dossierdepresse/encodage_articles/202_article.xml
> +               <quote rend="align(center)">
Merci ! Modification faite

2021-02-22 12:41 UTC, HugoSchtr commented on dossierdepresse/encodage_articles/202_article.xml
> +                  rend="align(center)">
merci ! modification faite

2021-02-22 12:44 UTC, HugoSchtr commented on dossierdepresse/encodage_articles/206_article.xml
> +                  <l>Je demande dans ma maison</l>
Merci ! J'ai ajouté une nouvelle entrée dans l'index des ref littéraires.

2021-02-22 12:44 UTC, HugoSchtr commented on dossierdepresse/encodage_articles/206_article.xml
> +                  <l>J'ai cueilli ce brin de bruyère.</l>
Merci ! modification faite

2021-02-22 12:45 UTC, HugoSchtr commented on dossierdepresse/encodage_articles/206_article.xml
> +               de la mer, se lèvent cha- <lb/>que jour pour le bonheur de tous. </p>
Modification faite!

2021-02-22 12:47 UTC, HugoSchtr commented on dossierdepresse/encodage_articles/206_article.xml
> +                  <l>Je passais au bord de la Seine,</l>
Merci ! Modification faite

2021-02-22 12:48 UTC, HugoSchtr commented
Merci beaucoup pour vos reviews ! J'ai fait les modifications dans les encodages individuels et m'apprête à les commit.

2021-02-23 09:00 UTC, D0riane commented on dossierdepresse/encodage_articles/articles_group.xml
> +                        <metamark function="header" rend="align(center) caps">A <persName
Non je pense qu'il s'agirait de faire un `rend="case(caps)"`. Comme nous pouvons le faire avec `rend= "align (center)` par exemple. Je suis pour et après ta confirmation je corrigerai également mes encodages.

2021-02-23 09:38 UTC, axellelecroq commented on dossierdepresse/encodage_articles/articles_group.xml
> +                        <metamark function="header" rend="align(center) caps">A <persName
Oui @D0riane c'est bien ce que je pensais. Excuse-moi Hugo pour le manque d'explicitations.

2021-02-23 09:43 UTC, HugoSchtr commented on dossierdepresse/encodage_articles/articles_group.xml
> +                        <metamark function="header" rend="align(center) caps">A <persName
Aucun problème ! Je suis d'accord sinon, je modifie mes encodages en fonction dans la journée. :)

2021-02-23 13:10 UTC, HugoSchtr commented
Toutes les modifications ont été faites. :) Si cela vous convient, la PR peut être merge.

2021-02-23 14:51 UTC, merged